/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package budgettracker;


import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author ADMIN
 */
public class BTFrame extends javax.swing.JFrame {
    private int balance =0;
    private int balance1 =0;
    private int balance2 =0;
    private int balance3 =0;
    
    File file = new File("History.txt");
    private final String filepath = file.getAbsolutePath();
    
    File file2 = new File("History2.txt");
    private final String filepath2 = file2.getAbsolutePath();
    
    
    static void selectRowtoJtable(Object[] object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
     DefaultTableModel model;
    /**
     * Creates new form BTFrame
     */
    public BTFrame() {
        initComponents();
        
        tableBudgetExpense.getTableHeader().setFont(new Font("Californian FB", Font.BOLD,12));
        tableBudgetExpense.getTableHeader().setOpaque(false);
        tableBudgetExpense.getTableHeader().setBackground(new Color(32,136,203));
        tableBudgetExpense.getTableHeader().setForeground(new Color(255,255,255));
        tableBudgetExpense.setColumnSelectionAllowed(false);
        tableBudgetExpense.setRowSelectionAllowed(true);
       
       
        tableBudgetIncome.getTableHeader().setFont(new Font("Californian FB", Font.BOLD,12));
        tableBudgetIncome.getTableHeader().setOpaque(false);
        tableBudgetIncome.getTableHeader().setBackground(new Color(32,136,203));
        tableBudgetIncome.getTableHeader().setForeground(new Color(255,255,255));
        tableBudgetIncome.setColumnSelectionAllowed(false);
        tableBudgetIncome.setRowSelectionAllowed(true);
       
 
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTotalMoney = new javax.swing.JLabel();
        JDate = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfDescription = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfAmount = new javax.swing.JTextField();
        btnExpense = new javax.swing.JButton();
        btnDeleteExpense = new javax.swing.JButton();
        btnIncome = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBudgetExpense = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblIncome = new javax.swing.JLabel();
        lblExpense = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableBudgetIncome = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        show_validation = new javax.swing.JLabel();
        btnDeleteIncome = new javax.swing.JButton();
        lblBalance = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(252, 246, 245));
        jPanel1.setForeground(new java.awt.Color(252, 246, 245));
        jPanel1.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(153, 0, 17));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 250, 250));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/budgettracker/BT Image (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(386, 386, 386)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        JDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JDateKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 17));
        jLabel4.setText("Date:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 17));
        jLabel5.setText("Enter Description:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 17));
        jLabel6.setText("Amount:");

        tfAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAmountActionPerformed(evt);
            }
        });
        tfAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfAmountKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfAmountKeyTyped(evt);
            }
        });

        btnExpense.setBackground(new java.awt.Color(153, 0, 17));
        btnExpense.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExpense.setForeground(new java.awt.Color(252, 246, 245));
        btnExpense.setText("EXPENSE");
        btnExpense.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExpenseMouseClicked(evt);
            }
        });
        btnExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpenseActionPerformed(evt);
            }
        });

        btnDeleteExpense.setBackground(new java.awt.Color(153, 0, 17));
        btnDeleteExpense.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDeleteExpense.setForeground(new java.awt.Color(252, 246, 245));
        btnDeleteExpense.setText("Delete Selected Expenses");
        btnDeleteExpense.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteExpenseMouseClicked(evt);
            }
        });
        btnDeleteExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteExpenseActionPerformed(evt);
            }
        });

        btnIncome.setBackground(new java.awt.Color(153, 0, 17));
        btnIncome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnIncome.setForeground(new java.awt.Color(252, 246, 245));
        btnIncome.setText("INCOME");
        btnIncome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIncomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIncomeMouseEntered(evt);
            }
        });
        btnIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncomeActionPerformed(evt);
            }
        });

        tableBudgetExpense.setAutoCreateRowSorter(true);
        tableBudgetExpense.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Description", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBudgetExpense.setColumnSelectionAllowed(true);
        tableBudgetExpense.setFocusable(false);
        tableBudgetExpense.setRowSelectionAllowed(false);
        tableBudgetExpense.setSelectionBackground(new java.awt.Color(168, 213, 186));
        tableBudgetExpense.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tableBudgetExpenseAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tableBudgetExpense.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBudgetExpenseMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableBudgetExpense);
        tableBudgetExpense.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/budgettracker/income.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/budgettracker/expense.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/budgettracker/CurrentBalance.png"))); // NOI18N

        lblIncome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIncome.setText("0");

        lblExpense.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblExpense.setForeground(new java.awt.Color(255, 0, 0));
        lblExpense.setText("0");

        tableBudgetIncome.setAutoCreateRowSorter(true);
        tableBudgetIncome.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Description", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBudgetIncome.setColumnSelectionAllowed(true);
        tableBudgetIncome.setFocusable(false);
        tableBudgetIncome.setRowSelectionAllowed(false);
        tableBudgetIncome.setSelectionBackground(new java.awt.Color(168, 213, 186));
        tableBudgetIncome.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tableBudgetIncomeAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tableBudgetIncome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBudgetIncomeMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableBudgetIncome);
        tableBudgetIncome.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        btnSave.setBackground(new java.awt.Color(153, 0, 17));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSave.setForeground(new java.awt.Color(252, 246, 245));
        btnSave.setText("Save Transactions");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/budgettracker/TotalIncome.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/budgettracker/TotalExpenses.png"))); // NOI18N

        show_validation.setForeground(new java.awt.Color(255, 0, 0));

        btnDeleteIncome.setBackground(new java.awt.Color(153, 0, 17));
        btnDeleteIncome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDeleteIncome.setForeground(new java.awt.Color(252, 246, 245));
        btnDeleteIncome.setText("Delete Selected Income");
        btnDeleteIncome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteIncomeMouseClicked(evt);
            }
        });
        btnDeleteIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteIncomeActionPerformed(evt);
            }
        });

        lblBalance.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBalance.setText("0");

        jLabel10.setText("Double click a row to be edited");

        jLabel11.setText("Double click a row to be edited");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JDate, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(776, 776, 776))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(185, 185, 185)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(157, 157, 157)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblIncome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(205, 205, 205)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnDeleteExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(show_validation, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(236, 236, 236))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(157, 157, 157)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblExpense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(138, 138, 138)
                                    .addComponent(btnExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(273, 273, 273)
                        .addComponent(lblTotalMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(368, 368, 368)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(btnDeleteIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTotalMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(264, 264, 264))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9)
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(lblBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(43, 43, 43)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lblExpense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnDeleteIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDeleteExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                    .addComponent(show_validation, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(tfDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(JDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1035, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAmountActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_tfAmountActionPerformed

    private void btnExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpenseActionPerformed
        // TODO add your handling code here:
        try{
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String date = dateFormat.format(JDate.getDate());
        DefaultTableModel model = (DefaultTableModel) tableBudgetExpense.getModel();
        
        // subtract cost to the total money
        double a = Double.parseDouble(tfAmount.getText());
 
        //display in table
            model.insertRow(model.getRowCount(),new Object[]{date,
            tfDescription.getText(), tfAmount.getText()});
        tfAmount.setText("");
        tfDescription.setText("");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Please fill up the form rightly", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
          
    }//GEN-LAST:event_btnExpenseActionPerformed

    private void btnDeleteExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteExpenseActionPerformed
        
        int del= JOptionPane.showConfirmDialog(null,"Are you sure you want to delete?","Delete",JOptionPane.YES_NO_OPTION);
        int newExpense = Integer.valueOf(lblExpense.getText());
        int newBalance = Integer.valueOf(lblBalance.getText());
        int selectedRowIndexExpense = tableBudgetExpense.getSelectedRow();
        if (del==0){
        try{
        DefaultTableModel model = (DefaultTableModel) tableBudgetExpense.getModel();
                    newExpense -= Integer.parseInt(tableBudgetExpense.getValueAt(selectedRowIndexExpense, 2).toString());
                    lblExpense.setText(Integer.toString(newExpense));
                    newBalance += Integer.parseInt(tableBudgetExpense.getValueAt(selectedRowIndexExpense, 2).toString());
                    lblBalance.setText(Integer.toString(newBalance));
                    model.removeRow(selectedRowIndexExpense);
        } catch ( Exception e){
      
        
        
       JOptionPane.showMessageDialog(this, "Please fill up the form rightly", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        }
    }//GEN-LAST:event_btnDeleteExpenseActionPerformed
        
    private void btnIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncomeActionPerformed
       
        //date format
        try{
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String date = dateFormat.format(JDate.getDate());
            DefaultTableModel model = (DefaultTableModel) tableBudgetIncome.getModel();
        
         double a = Double.parseDouble(tfAmount.getText());
         
         
        //display in table
            model.insertRow(model.getRowCount(),new Object[]{date,
            tfDescription.getText(), tfAmount.getText()});
            tfAmount.setText("");
            tfDescription.setText("");
        
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Please fill up the form rightly", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnIncomeActionPerformed

    private void btnExpenseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExpenseMouseClicked
        int diff = 0;
        int totalIncome = 0;
     
                  for(int i = 0; i < tableBudgetExpense.getRowCount(); i++){
                      diff = diff + Integer.parseInt((String) tableBudgetExpense.getValueAt(i, 2));
                  }
                    lblExpense.setText(Integer.toString(diff));
                    
                    int totalExpense = Integer.parseInt(lblExpense.getText());
                    totalIncome = Integer.parseInt(lblIncome.getText());
                    int balance = totalIncome - totalExpense;
                    
                    lblBalance.setText(Integer.toString(balance));
    }//GEN-LAST:event_btnExpenseMouseClicked

    private void btnIncomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIncomeMouseClicked
          int sum = 0;
          int totalExpense = 0;
     
                  for(int i = 0; i < tableBudgetIncome.getRowCount(); i++){
                      sum = sum + Integer.parseInt((String) tableBudgetIncome.getValueAt(i, 2));
                  }
                    lblIncome.setText(Integer.toString(sum));
                    
                    totalExpense = Integer.parseInt(lblExpense.getText());
                    int totalIncome = Integer.parseInt(lblIncome.getText());
                    int balance = totalIncome - totalExpense;
                        
                    lblBalance.setText(Integer.toString(balance));
                    
    }//GEN-LAST:event_btnIncomeMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
      try{
            FileWriter fw = new FileWriter(filepath);
            BufferedWriter bw = new BufferedWriter(fw);
            for (int i = 0; i <tableBudgetIncome.getRowCount(); i++) {
                for (int j = 0; j <tableBudgetIncome.getColumnCount(); j++) {
                    bw.write(tableBudgetIncome.getValueAt(i, j).toString()+ "/");
                }
                bw.newLine();
            }
            bw.close();
            fw.close();
            JOptionPane.showMessageDialog(null, "Save Succesfully");

        }catch (IOException e) {
            JOptionPane.showMessageDialog(null, "error");
        }
        try{
            FileWriter fw = new FileWriter(filepath2);
            BufferedWriter bw = new BufferedWriter(fw);
            for (int i = 0; i <tableBudgetExpense.getRowCount(); i++) {
                for (int j = 0; j <tableBudgetExpense.getColumnCount(); j++) {
                    bw.write(tableBudgetExpense.getValueAt(i, j).toString()+ "/");
                }
                bw.newLine();
            }
            bw.close();
            fw.close();
           

        }catch (IOException e) {
           
        }
                      
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteExpenseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteExpenseMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteExpenseMouseClicked

    private void tfAmountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfAmountKeyPressed
     
  
    }//GEN-LAST:event_tfAmountKeyPressed

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveMouseClicked

    private void btnDeleteIncomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteIncomeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteIncomeMouseClicked

    private void btnDeleteIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteIncomeActionPerformed
        int del= JOptionPane.showConfirmDialog(null,"Are you sure you want to delete?","Delete",JOptionPane.YES_NO_OPTION);
        
        int newIncome =  Integer.valueOf(lblIncome.getText());
        int selectedRowIndexIncome = tableBudgetIncome.getSelectedRow();
        int newBalance = Integer.valueOf(lblBalance.getText());
       
        if (del == 0){
             try{
                    DefaultTableModel model1 = (DefaultTableModel) tableBudgetIncome.getModel();
                    newIncome -= Integer.parseInt(tableBudgetIncome.getValueAt(selectedRowIndexIncome, 2).toString());
                    lblIncome.setText(Integer.toString(newIncome));
                    newBalance -= Integer.parseInt(tableBudgetIncome.getValueAt(selectedRowIndexIncome, 2).toString());
                    lblBalance.setText(Integer.toString(newBalance));
                    model1.removeRow(selectedRowIndexIncome);
             }catch(Exception e){
                 JOptionPane.showMessageDialog(this, "Please fill up the form rightly", "Error", JOptionPane.ERROR_MESSAGE);

             }
        }
    }//GEN-LAST:event_btnDeleteIncomeActionPerformed

    private void tableBudgetIncomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBudgetIncomeMouseClicked
      
        DefaultTableModel model = (DefaultTableModel)tableBudgetIncome.getModel();
    
        
        //get table value income and description
        if(evt.getClickCount()== 2){
            int counter = tableBudgetIncome.getSelectedRow();
            tfAmount.setText(tableBudgetIncome.getValueAt(counter, 2).toString());
            tfDescription.setText(tableBudgetIncome.getValueAt(counter, 1).toString());
        
        //get table value date
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            try{
                Date date = dateFormat.parse(tableBudgetIncome.getValueAt(counter,0).toString());
                JDate.setDate(date);
            } catch(ParseException ex){
                Logger.getLogger(BudgetTracker.class.getName()).log(Level.SEVERE,null,ex);
            }
        //#############################################################################
        
            int getTableIncome = tableBudgetIncome.getSelectedRow();
            int newBalance = Integer.valueOf(lblBalance.getText());
            int newIncome = Integer.valueOf(lblIncome.getText());
            
                newBalance -=Integer.parseInt(tableBudgetIncome.getValueAt(getTableIncome, 2).toString());
                newIncome -=Integer.parseInt(tableBudgetIncome.getValueAt(getTableIncome, 2).toString());
            
            lblBalance.setText(String.valueOf(newBalance));
            lblIncome.setText(String.valueOf(newIncome));
            model.removeRow(getTableIncome);
        }
    }//GEN-LAST:event_tableBudgetIncomeMouseClicked

    private void tableBudgetExpenseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBudgetExpenseMouseClicked
        
        DefaultTableModel model1 = (DefaultTableModel)tableBudgetExpense.getModel();
    
        
        //get table value income and description
        if(evt.getClickCount()== 2){
            int counter = tableBudgetExpense.getSelectedRow();
            tfAmount.setText(tableBudgetExpense.getValueAt(counter, 2).toString());
            tfDescription.setText(tableBudgetExpense.getValueAt(counter, 1).toString());
        
        //get table value date
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            try{
                Date date = dateFormat.parse(tableBudgetExpense.getValueAt(counter,0).toString());
                JDate.setDate(date);
            } catch(ParseException ex){
                Logger.getLogger(BudgetTracker.class.getName()).log(Level.SEVERE,null,ex);
            }
        //#############################################################################
        
            int getTableExpense = tableBudgetExpense.getSelectedRow();
            int newBalance = Integer.valueOf(lblBalance.getText());
            int newExpense = Integer.valueOf(lblExpense.getText());
            
                newBalance +=Integer.parseInt(tableBudgetExpense.getValueAt(getTableExpense, 2).toString());
                newExpense -=Integer.parseInt(tableBudgetExpense.getValueAt(getTableExpense, 2).toString());
            
            lblBalance.setText(String.valueOf(newBalance));
            lblExpense.setText(String.valueOf(newExpense));
            model1.removeRow(getTableExpense);
        }
    }//GEN-LAST:event_tableBudgetExpenseMouseClicked

    private void tableBudgetIncomeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tableBudgetIncomeAncestorAdded
    
        //saving income
       try{
            BufferedReader br = new BufferedReader(new FileReader (file));

            DefaultTableModel model = (DefaultTableModel)tableBudgetIncome.getModel();
            for (int counter = model.getRowCount() - 1; counter>=0; counter--){
                model.removeRow(counter);
            }

            Object[] tableLines = br.lines().toArray();

            if(model.getRowCount()>0){
                for(int count = model.getRowCount() - 1; count >= 0; count--){
                    model.removeRow(count);
                }
            }
            for (int i = 0; i <tableLines.length; i++) {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split("/");
                model.addRow(dataRow);
            }

            balance3 = 0;

            for(int i =0; i<tableBudgetIncome.getRowCount(); i++){
                    balance3 += Integer.parseInt(tableBudgetIncome.getValueAt(i, 2).toString());
                    balance2+=Integer.parseInt(tableBudgetIncome.getValueAt(i, 2).toString());
            }
            
            lblIncome.setText(String.valueOf(balance2));
            
            if(tableBudgetExpense.getRowCount()== 0){
                lblBalance.setText(Integer.toString(balance3));
            }else{
                int totalExpense = 0;
                totalExpense = Integer.parseInt(lblExpense.getText());
                    int totalIncome = Integer.parseInt(lblIncome.getText());
                    int balance = totalIncome - totalExpense;
                        
                    lblBalance.setText(Integer.toString(balance));
            }
            
            

        }catch (Exception e) {

        }
       //saving expense
       try{
            BufferedReader br1 = new BufferedReader(new FileReader (file2));

            DefaultTableModel model = (DefaultTableModel)tableBudgetExpense.getModel();
            for (int counter = model.getRowCount() - 1; counter>=0; counter--){
                model.removeRow(counter);
            }

            Object[] tableLines1 = br1.lines().toArray();

            if(model.getRowCount()>0){
                for(int count = model.getRowCount() - 1; count >= 0; count--){
                    model.removeRow(count);
                }
            }
            for (int i = 0; i <tableLines1.length; i++) {
                String line = tableLines1[i].toString().trim();
                String[] dataRow = line.split("/");
                model.addRow(dataRow);
            }

            balance = 0;
            

            for(int i =0; i<tableBudgetExpense.getRowCount(); i++){
                    balance -= Integer.parseInt(tableBudgetExpense.getValueAt(i, 2).toString());
                    balance1+=Integer.parseInt(tableBudgetExpense.getValueAt(i, 2).toString());
            }
            
            lblExpense.setText(String.valueOf(balance1));
            
            if(tableBudgetIncome.getRowCount() == 0){
            lblBalance.setText(Integer.toString(balance));
            }
            else{
                   int totalIncome = 0;
                   int totalExpense = Integer.parseInt(lblExpense.getText());
                    totalIncome = Integer.parseInt(lblIncome.getText());
                    int balance = totalIncome - totalExpense;
                    
                    lblBalance.setText(Integer.toString(balance));
            }

            
        }catch(Exception e){
        }
    }//GEN-LAST:event_tableBudgetIncomeAncestorAdded

    private void tableBudgetExpenseAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tableBudgetExpenseAncestorAdded
    try{
            
        }catch (Exception e) {

        }
    }//GEN-LAST:event_tableBudgetExpenseAncestorAdded

    private void btnIncomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIncomeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIncomeMouseEntered

    private void tfAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfAmountKeyTyped
          char c = evt.getKeyChar();
        if(!(Character.isDigit(c)|| (c == KeyEvent.VK_BACK_SPACE)
                ||c==KeyEvent.VK_DELETE)){
            evt.consume();
            
        }
         
    }//GEN-LAST:event_tfAmountKeyTyped

    private void JDateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JDateKeyTyped
        
       
    }//GEN-LAST:event_JDateKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BTFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BTFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BTFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BTFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BTFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JDate;
    private javax.swing.JButton btnDeleteExpense;
    private javax.swing.JButton btnDeleteIncome;
    private javax.swing.JButton btnExpense;
    private javax.swing.JButton btnIncome;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblExpense;
    private javax.swing.JLabel lblIncome;
    private javax.swing.JLabel lblTotalMoney;
    private javax.swing.JLabel show_validation;
    private javax.swing.JTable tableBudgetExpense;
    private javax.swing.JTable tableBudgetIncome;
    private javax.swing.JTextField tfAmount;
    private javax.swing.JTextField tfDescription;
    // End of variables declaration//GEN-END:variables
}
